from __future__ import annotations

from typing import Any

import onnxruntime as ort

from narh_yolo_align.backends.pytorch_yolo import PreprocessBatch


class ONNXYOLOBackend:
    """Target backend for ONNX Runtime.

    v0.1 parity rule:
    ONNX backend does not implement image preprocessing. It receives the exact
    tensor generated by PyTorchYOLOBackend.preprocess().
    """

    def __init__(self, model_path: str, *, providers: list[str] | None = None):
        providers = providers or ["CPUExecutionProvider"]
        self.session = ort.InferenceSession(model_path, providers=providers)
        inputs = self.session.get_inputs()
        if not inputs:
            raise ValueError("ONNX model has no inputs")
        self.input_name = inputs[0].name

    def raw_forward(self, batch: PreprocessBatch) -> Any:
        """Run ONNX inference on the exact shared tensor."""
        x = batch.tensor.detach().cpu().numpy()
        return self.session.run(None, {self.input_name: x})
