from __future__ import annotations

from typing import Any

import numpy as np
import onnxruntime as ort

from narh_yolo_align.backends.pytorch_yolo import PreprocessBatch


def _dtype_from_onnx_input_type(input_type: str) -> np.dtype:
    """Map ONNX Runtime input type string to numpy dtype."""
    normalized = (input_type or "").lower()
    if "float16" in normalized:
        return np.float16
    if "double" in normalized or "float64" in normalized:
        return np.float64
    # Default for Ultralytics ONNX exports.
    return np.float32


class ONNXYOLOBackend:
    """Target backend for ONNX Runtime.

    v0.1 parity rule:
    ONNX backend does not implement image preprocessing. It receives the exact
    tensor generated by PyTorchYOLOBackend.preprocess().
    """

    def __init__(self, model_path: str, *, providers: list[str] | None = None):
        providers = providers or ["CPUExecutionProvider"]
        self.session = ort.InferenceSession(model_path, providers=providers)

        inputs = self.session.get_inputs()
        if not inputs:
            raise ValueError("ONNX model has no inputs")

        self.input_name = inputs[0].name
        self.input_type = inputs[0].type
        self.input_dtype = _dtype_from_onnx_input_type(self.input_type)

    def raw_forward(self, batch: PreprocessBatch) -> Any:
        """Run ONNX inference on the exact shared tensor.

        Dtype alignment:
        If PyTorch preprocessing returns float16, ONNX CPUExecutionProvider may
        still expect float32. Always cast to the model input dtype.
        """
        x = batch.tensor.detach().cpu().numpy().astype(self.input_dtype, copy=False)
        outputs = self.session.run(None, {self.input_name: x})
        return outputs
