from __future__ import annotations

from pathlib import Path
from typing import Dict, List
import csv
import json
import shutil

import yaml

from narh_yolo_align.residuals import ImageResidual


HIGH_RESIDUAL_BUCKETS = ["critical_disagreement", "threshold_crossing", "score_drift_heavy", "box_iou_drift"]


def build_calibration_set(
    grouped: Dict[str, List[ImageResidual]],
    *,
    out_dir: str | Path,
    max_images: int = 500,
    representative_ratio: float = 0.70,
) -> List[ImageResidual]:
    """Build residual-balanced calibration image set.

    v0.1 strategy:
    - 70% representative_consistent
    - 30% highest residual frames from all non-representative buckets

    This is for INT8 calibration/export, not supervised training labels.
    """
    cal_root = Path(out_dir) / "calibration_set"
    images_dir = cal_root / "images"
    images_dir.mkdir(parents=True, exist_ok=True)

    rep_count = int(max_images * representative_ratio)
    residual_count = max_images - rep_count
    representatives = grouped.get("representative_consistent", [])[:rep_count]

    high_residual: List[ImageResidual] = []
    for bucket in HIGH_RESIDUAL_BUCKETS:
        high_residual.extend(grouped.get(bucket, []))
    high_residual.sort(key=lambda x: x.residual_score, reverse=True)
    high_residual = high_residual[:residual_count]
    selected = representatives + high_residual

    with (cal_root / "manifest.csv").open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=["image", "bucket", "residual_score", "reasons", "metrics_json"])
        writer.writeheader()
        for r in selected:
            src = Path(r.image_path)
            dst = images_dir / src.name
            if src.exists():
                shutil.copy2(src, dst)
            writer.writerow({
                "image": str(dst.relative_to(cal_root)),
                "bucket": r.bucket,
                "residual_score": f"{r.residual_score:.6f}",
                "reasons": "; ".join(r.reasons),
                "metrics_json": json.dumps(r.metrics, ensure_ascii=False),
            })

    data_yaml = {
        "path": str(cal_root.resolve()),
        "train": "images",
        "val": "images",
        "names": {0: "calibration_image"},
        "narh_note": "Label-free calibration image set for INT8 export. This file does not contain YOLO ground-truth labels.",
    }
    with (cal_root / "data.yaml").open("w", encoding="utf-8") as f:
        yaml.safe_dump(data_yaml, f, sort_keys=False, allow_unicode=True)

    (cal_root / "README.md").write_text(
        "# Calibration Set\n\nThis is a label-free calibration image set generated by NARH-YOLO Align.\n\nIt is intended for INT8 calibration/export workflows, not supervised training.\n",
        encoding="utf-8",
    )
    return selected
